const data =
{
  products:
  [
      {
        _id:'1',
        name: 'Nike Slim Shirts',
        category: 'Shirts',
        image:'/images/p1.png',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'High quality product',
    },
    {
      _id:'2',
      name: 'Nike Slim Shirts',
      category: 'Shirts',
      image:'/images/p1.png',
      price: 140,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      _id:'3',
      name: 'Nike Slim Shirts',
      category: 'Shirts',
      image:'/images/p1.png',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      _id:'4',
      name: 'Nike Slim Shirts',
      category: 'Shirts',
      image:'/images/p1.png',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      _id:'5',
      name: 'Nike Slim Shirts',
      category: 'Shirts',
      image:'/images/p1.png',
      price: 200,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
  ],
}

export default data;
